### ISSUE TITLE
关于用户购买或更换服务器规格的建议

### ISSUE THREAD

**Issue by 59xs** [huaweicloudDocs/ecs#2]
能不能在已售罄的服务器下面增加一个到货提醒的功能，就是当服务器有上新时对我进行通知，不用我每天都去看某种已售罄服务器到货了没。没开启这个功能则不会提醒，开启后到货提醒一次。（可以是短信或者邮件的方式）

**Comment by Miss-Qiao** [comment]
感谢您提出的宝贵意见，我们已接收该需求并在内部讨论中，如有一下一步的计划和进展我们将再次通知您。
