### ISSUE TITLE
查看监控指标章节操作场景和前提条件建议精简优化

### ISSUE THREAD

**Issue by fighting-go-go-go** [huaweicloudDocs/ecs#5]
操作场景第二段和前提条件的第一点和第三点感觉内容稍冗余，建议精简一下。想表达的意思应该都是ECS正常运行一段时间。

**Comment by suxiaomeng1** [comment]
感谢你提出的修改建议，我们重新检查了“查看监控指标”章节的操作场景和前提条件的描述信息。
操作场景告知用户云监控可以帮助用户监控云服务器日常运行状态。同时告知用户监控指标的传输需要时间。新创建的云服务器需要等待5-10分钟才可以查看监控数据。

前提条件的写作要求是指特定角色执行操作前系统要达到的状态和需要准备好的数据。因此前提条件中列出要求云服务器运行状态、且正常运行了一段时间是正确的。
