### ISSUE TITLE
资料中提及的联系客服、技术支持或提交工单的疑问和建议

### ISSUE THREAD

**Issue by fighting-go-go-go** [huaweicloudDocs/ecs#6]
搜索全部的ECS资料，包括用户指南，常见问题等，出现多次联系联系客服、技术支持或提交工单的描述。有个疑问是以上三种描述是否有较明确的场景。目前看有混用的情况。请考虑是否需要优化改进，谢谢。

**Comment by suxiaomeng1** [comment]
感谢您提出的修改建议，我们将重新检查ECS资料中关于客服、技术支持、提交工单的相关描述，规范化修改后再进一步答复。

**Comment by suxiaomeng1** [comment]
你好 感谢您提出的修改意见，我们已重新优化资料内容，将客服、技术支持、提交工单的类似描述统一规范化使用为联系客服，或联系客服获取技术支持。
